apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: energy-prometheus-exporter
  name: energy-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-prometheus-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: energy-prometheus-exporter
    spec:
      containers:
        - name: exporter
          env:
            - name: HOMEWIZARD_URL
              valueFrom:
                secretKeyRef:
                  name: homewizard
                  key: url
            - name: HOMEWIZARD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homewizard
                  key: token
            - name: SOLAREDGE_HOST
              value: "{{ .Values.solaredge.host }}"
            - name: SOLAREDGE_PORT
              value: "{{ .Values.solaredge.port }}"
          image: {{ .Values.pod.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: {{ .Values.exporter.port }}
          readinessProbe:
            httpGet:
              path: /health-check
              port: {{ .Values.exporter.port }}
            initialDelaySeconds: 3
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
      nodeSelector:
        worker: "true"
